<?php

return [

'Customer Identity' => [

'msisdn' => [
'label' => 'MSISDN',
'definition' => 'The phone number used when the customer made a payment. This acts as the unique identifier for the customer across the entire system. All transactions linked to this phone number are grouped together to build the full customer profile.'
],

'first_name' => [
'label' => 'First Name',
'definition' => 'The customer name captured during payment. This is used mainly for personalization and identifying repeat customers in reports.'
],

'gender' => [
'label' => 'Gender',
'definition' => 'The gender inferred from payment metadata. This field is used only for demographic analysis and understanding customer composition.'
],

],

'Customer Timeline' => [

'first_transaction' => [
'label' => 'First Transaction',
'definition' => 'The date and time when this customer made their first recorded payment. This marks the beginning of the relationship between the business and the customer.'
],

'last_transaction' => [
'label' => 'Last Transaction',
'definition' => 'The date and time of the most recent payment made by the customer. This shows when the customer last visited or interacted with the business.'
],

'customer_age_days' => [
'label' => 'Customer Age (Days)',
'definition' => 'The total number of days since the customer first interacted with the business. It is calculated as: Current Date minus First Transaction Date. This metric shows how long the relationship with the customer has existed.'
],

'customer_age_months' => [
'label' => 'Customer Age (Months)',
'definition' => 'The customer age converted into months. This is used to normalize other metrics such as visit frequency and monthly spending.'
],

'days_since_last' => [
'label' => 'Days Since Last Visit',
'definition' => 'The number of days that have passed since the customer last made a payment. This helps identify inactive customers and is important for churn analysis.'
],

],

'Spending Metrics' => [

'all_time_spend' => [
'label' => 'All-Time Spend',
'definition' => 'The total amount of money the customer has spent across all recorded transactions. This metric represents the total lifetime revenue generated from this customer.'
],

'average_spend' => [
'label' => 'Average Spend',
'definition' => 'The typical amount the customer spends during a single visit. It is calculated as: Total Spend divided by Total Transactions. This metric helps identify the spending power of the customer.'
],

'highest_transaction' => [
'label' => 'Highest Transaction',
'definition' => 'The largest single payment ever made by the customer. High values may indicate group visits, events, or special occasions.'
],

'lowest_transaction' => [
'label' => 'Lowest Transaction',
'definition' => 'The smallest payment recorded from the customer. This provides context for the lower bound of the customer spending range.'
],

'all_time_transactions' => [
'label' => 'Total Transactions',
'definition' => 'The total number of payments made by the customer. This represents how many times the customer has visited or interacted with the business.'
],

],

'Visit Behavior' => [

'average_return_interval_days' => [
'label' => 'Average Return Interval',
'definition' => 'The average number of days between each customer visit. It is calculated by measuring the difference between transaction dates and averaging the intervals. Lower values mean the customer returns more frequently.'
],

'longest_interval_days' => [
'label' => 'Longest Visit Gap',
'definition' => 'The longest period of inactivity between two visits. This shows the maximum time the customer stayed away before returning.'
],

'visit_frequency_per_month' => [
'label' => 'Visits Per Month',
'definition' => 'The average number of visits the customer makes each month. It is calculated as Total Transactions divided by Customer Age in Months.'
],

'spend_velocity_per_month' => [
'label' => 'Spend Velocity Per Month',
'definition' => 'The average monthly revenue generated by the customer. It is calculated as Total Spend divided by Customer Age in Months.'
],

],

'Revenue Contribution' => [

'revenue_share_percent' => [
'label' => 'Revenue Share',
'definition' => 'The percentage of total business revenue that comes from this customer. It is calculated as Customer Spend divided by Total Business Revenue. Higher values indicate customers who contribute significantly to overall income.'
],

],

'Customer Ranking' => [

'customer_rank' => [
'label' => 'Customer Rank',
'definition' => 'The ranking position of the customer when all customers are ordered by total spending. Rank 1 represents the highest spending customer.'
],

'top_spender_percentile' => [
'label' => 'Top Spender Percentile',
'definition' => 'The percentile ranking of the customer among all customers based on spending. For example, a value of 0.05 means the customer is among the top 0.05 percent of spenders.'
],

'spending_segment' => [
'label' => 'Spending Segment',
'definition' => 'Customers are grouped into segments based on their spending percentile. For example: Whale (top 1%), VIP (top 5%), High Value (top 10%), Regular (top 50%), and Low Value (remaining customers).'
],

],

'Customer Loyalty & Lifecycle' => [

'loyalty_tier' => [
'label' => 'Loyalty Tier',
'definition' => 'A loyalty classification used to group customers by value and engagement. Typical tiers include Bronze, Silver, Gold, Platinum, and Diamond. Higher tiers represent more valuable and loyal customers.'
],

'lifecycle_stage' => [
'label' => 'Lifecycle Stage',
'definition' => 'The stage of the customer relationship based on visit count. For example: New (first visit), Exploring (2–3 visits), Regular (4–10 visits), Loyal (11–30 visits), and VIP (more than 30 visits).'
],

],

'Churn Prediction' => [

'churn_risk' => [
'label' => 'Churn Risk',
'definition' => 'A classification indicating the likelihood that the customer may stop visiting the business. The risk level is determined using the delay between visits compared to the normal visit interval.'
],

'churn_probability' => [
'label' => 'Churn Probability',
'definition' => 'The estimated probability that the customer may stop returning. It is calculated using the ratio between the time since the last visit and the customer’s normal visit interval.'
],

],

'Customer Value Prediction' => [

'predicted_next_visit' => [
'label' => 'Predicted Next Visit',
'definition' => 'An estimated date when the customer is expected to return. This is calculated using the customer’s historical visit interval.'
],

'predicted_lifetime_value' => [
'label' => 'Predicted Lifetime Value',
'definition' => 'The estimated revenue that the customer is expected to generate over the next 12 months. It is calculated using average spend and visit frequency.'
],

],

'Growth & Engagement' => [

'spending_growth_rate' => [
'label' => 'Spending Growth Rate',
'definition' => 'Measures whether the customer spending is increasing or decreasing over time. Positive values indicate that the customer is spending more with each visit.'
],

'engagement_score' => [
'label' => 'Engagement Score',
'definition' => 'A composite score that measures how active the customer is. It combines factors such as visit frequency, spending velocity, and RFM score.'
],

'visit_consistency_score' => [
'label' => 'Visit Consistency Score',
'definition' => 'A measure of how predictable the customer visit pattern is. Customers who visit at regular intervals will have higher scores.'
],

],

'Visit Timing Behavior' => [

'weekday_visit_ratio' => [
'label' => 'Weekday Visit Ratio',
'definition' => 'The percentage of visits that occur during weekdays. This helps identify whether the customer prefers weekday visits.'
],

'weekend_visit_ratio' => [
'label' => 'Weekend Visit Ratio',
'definition' => 'The percentage of visits that occur during weekends.'
],

'morning_visit_ratio' => [
'label' => 'Morning Visit Ratio',
'definition' => 'The percentage of visits that occur during the morning hours.'
],

'afternoon_visit_ratio' => [
'label' => 'Afternoon Visit Ratio',
'definition' => 'The percentage of visits that occur during the afternoon.'
],

'evening_visit_ratio' => [
'label' => 'Evening Visit Ratio',
'definition' => 'The percentage of visits that occur during the evening hours.'
],

'night_visit_ratio' => [
'label' => 'Night Visit Ratio',
'definition' => 'The percentage of visits that occur during night hours.'
],

'most_common_visit_time' => [
'label' => 'Most Common Visit Time',
'definition' => 'The time period during which the customer most frequently visits.'
],

'most_common_visit_day' => [
'label' => 'Most Common Visit Day',
'definition' => 'The type of day when the customer most frequently visits, either weekday or weekend.'
],

],

'Payment Behavior' => [

'favorite_reference' => [
'label' => 'Favorite Payment Reference',
'definition' => 'The payment reference that the customer uses most frequently. This may indicate common purchases or recurring services.'
],

'preferred_shortcode' => [
'label' => 'Preferred Paybill',
'definition' => 'The paybill or shortcode most commonly used by the customer when making payments.'
],

'first_reference' => [
'label' => 'First Payment Reference',
'definition' => 'The reference used in the very first payment recorded for this customer.'
],

'first_shortcode' => [
'label' => 'First Paybill',
'definition' => 'The paybill used during the customer’s first payment.'
],

],

'System Metadata' => [

'anomaly_flag' => [
'label' => 'Anomaly Flag',
'definition' => 'Indicates whether unusual patterns have been detected in the customer’s behavior. This may include sudden spikes in spending or abnormal visit patterns.'
],

'profile_created_at' => [
'label' => 'Profile Created',
'definition' => 'The timestamp when the customer intelligence profile was generated.'
],

'profile_updated_at' => [
'label' => 'Profile Updated',
'definition' => 'The timestamp when the customer profile was last recalculated or updated.'
],

]

];