<?php

declare(strict_types=1);

/**
 * Customer metric definitions.
 * Each section contains metric keys mapped to label + definition.
 * Used by CustomerMetricsService to build structured sections
 * from a raw customer_profiles DB row.
 */
return [

    'Identity & Overview' => [

        'first_name' => [
            'label'      => 'First Name',
            'definition' => 'The first name of the customer as recorded during their first transaction.',
        ],

        'gender' => [
            'label'      => 'Gender',
            'definition' => 'The gender of the customer as detected from their name.',
        ],

        'msisdn' => [
            'label'      => 'Phone Number',
            'definition' => 'The mobile number used by the customer for all recorded transactions.',
        ],

        'first_transaction' => [
            'label'      => 'First Transaction',
            'definition' => 'The date and time of the first ever payment recorded from this customer.',
        ],

        'last_transaction' => [
            'label'      => 'Last Transaction',
            'definition' => 'The date and time of the most recent payment recorded from this customer.',
        ],

        'customer_age_days' => [
            'label'      => 'Customer Age (Days)',
            'definition' => 'The number of days since the customer first made a payment at this business.',
        ],

        'customer_age_months' => [
            'label'      => 'Customer Age (Months)',
            'definition' => 'The number of months since the customer first made a payment.',
        ],

        'days_since_last' => [
            'label'      => 'Days Since Last Visit',
            'definition' => 'The number of days that have passed since the customer last made a payment.',
        ],

    ],

    'Spending Statistics' => [

        'all_time_spend' => [
            'label'      => 'All Time Spend',
            'definition' => 'The total amount of money spent by the customer across all recorded transactions.',
        ],

        'average_spend' => [
            'label'      => 'Average Spend',
            'definition' => 'The average transaction value. It is calculated as: Total Spend divided by Total Transactions.',
        ],

        'highest_transaction' => [
            'label'      => 'Highest Transaction',
            'definition' => 'The largest single payment ever made by the customer.',
        ],

        'lowest_transaction' => [
            'label'      => 'Lowest Transaction',
            'definition' => 'The smallest payment recorded from the customer.',
        ],

        'all_time_transactions' => [
            'label'      => 'Total Transactions',
            'definition' => 'The total number of payments made by the customer.',
        ],

    ],

    'Visit Behavior' => [

        'average_return_interval_days' => [
            'label'      => 'Average Return Interval',
            'definition' => 'The average number of days between each customer visit.',
        ],

        'longest_interval_days' => [
            'label'      => 'Longest Visit Gap',
            'definition' => 'The longest period of inactivity between two visits.',
        ],

        'visit_frequency_per_month' => [
            'label'      => 'Visits Per Month',
            'definition' => 'The average number of visits the customer makes each month.',
        ],

        'spend_velocity_per_month' => [
            'label'      => 'Spend Velocity Per Month',
            'definition' => 'The average monthly revenue generated by the customer.',
        ],

    ],

    'Revenue Contribution' => [

        'revenue_share_percent' => [
            'label'      => 'Revenue Share',
            'definition' => 'The percentage of total business revenue that comes from this customer.',
        ],

    ],

    'Customer Ranking' => [

        'customer_rank' => [
            'label'      => 'Customer Rank',
            'definition' => 'The ranking position of the customer when all customers are ordered by total spending. Rank 1 represents the highest spending customer.',
        ],

        'top_spender_percentile' => [
            'label'      => 'Top Spender Percentile',
            'definition' => 'The percentile ranking of the customer among all customers based on spending.',
        ],

        'spending_segment' => [
            'label'      => 'Spending Segment',
            'definition' => 'Customers are grouped into segments based on their spending percentile. Whale (top 1%), VIP (top 5%), High Value (top 10%), Regular (top 50%), Low Value (remaining).',
        ],

    ],

    'Customer Loyalty & Lifecycle' => [

        'loyalty_tier' => [
            'label'      => 'Loyalty Tier',
            'definition' => 'A loyalty classification used to group customers by value and engagement. Tiers: Bronze, Silver, Gold, Platinum, Diamond.',
        ],

        'lifecycle_stage' => [
            'label'      => 'Lifecycle Stage',
            'definition' => 'The stage of the customer relationship based on visit count.',
        ],

    ],

    'Churn Prediction' => [

        'churn_risk' => [
            'label'      => 'Churn Risk',
            'definition' => 'A classification indicating the likelihood that the customer may stop visiting the business.',
        ],

        'churn_probability' => [
            'label'      => 'Churn Probability',
            'definition' => 'The estimated probability that the customer may stop returning.',
        ],

    ],

    'Customer Value Prediction' => [

        'predicted_next_visit' => [
            'label'      => 'Predicted Next Visit',
            'definition' => 'An estimated date when the customer is expected to return.',
        ],

        'predicted_lifetime_value' => [
            'label'      => 'Predicted Lifetime Value',
            'definition' => 'The estimated revenue the customer is expected to generate over the next 12 months.',
        ],

    ],

    'Growth & Engagement' => [

        'spending_growth_rate' => [
            'label'      => 'Spending Growth Rate',
            'definition' => 'Measures whether the customer spending is increasing or decreasing over time.',
        ],

        'engagement_score' => [
            'label'      => 'Engagement Score',
            'definition' => 'A composite score combining visit frequency, spending velocity, and RFM score.',
        ],

        'visit_consistency_score' => [
            'label'      => 'Visit Consistency Score',
            'definition' => 'A measure of how predictable the customer visit pattern is.',
        ],

    ],

    'Visit Timing Behavior' => [

        'weekday_visit_ratio' => [
            'label'      => 'Weekday Visit Ratio',
            'definition' => 'The percentage of visits that occur during weekdays.',
        ],

        'weekend_visit_ratio' => [
            'label'      => 'Weekend Visit Ratio',
            'definition' => 'The percentage of visits that occur during weekends.',
        ],

        'morning_visit_ratio' => [
            'label'      => 'Morning Visit Ratio',
            'definition' => 'The percentage of visits that occur during the morning hours.',
        ],

        'afternoon_visit_ratio' => [
            'label'      => 'Afternoon Visit Ratio',
            'definition' => 'The percentage of visits that occur during the afternoon.',
        ],

        'evening_visit_ratio' => [
            'label'      => 'Evening Visit Ratio',
            'definition' => 'The percentage of visits that occur during the evening hours.',
        ],

        'night_visit_ratio' => [
            'label'      => 'Night Visit Ratio',
            'definition' => 'The percentage of visits that occur during night hours.',
        ],

        'most_common_visit_time' => [
            'label'      => 'Most Common Visit Time',
            'definition' => 'The time period during which the customer most frequently visits.',
        ],

        'most_common_visit_day' => [
            'label'      => 'Most Common Visit Day',
            'definition' => 'The type of day when the customer most frequently visits.',
        ],

    ],

    'Payment Behavior' => [

        'favorite_reference' => [
            'label'      => 'Favorite Payment Reference',
            'definition' => 'The payment reference that the customer uses most frequently.',
        ],

        'preferred_shortcode' => [
            'label'      => 'Preferred Paybill',
            'definition' => 'The paybill or shortcode most commonly used by the customer.',
        ],

        'first_reference' => [
            'label'      => 'First Payment Reference',
            'definition' => 'The reference used in the very first payment recorded for this customer.',
        ],

        'first_shortcode' => [
            'label'      => 'First Paybill',
            'definition' => 'The paybill used during the customer\'s first payment.',
        ],

    ],

    'System Metadata' => [

        'anomaly_flag' => [
            'label'      => 'Anomaly Flag',
            'definition' => 'Indicates whether unusual patterns have been detected in the customer\'s behavior.',
        ],

        'profile_created_at' => [
            'label'      => 'Profile Created',
            'definition' => 'The timestamp when the customer intelligence profile was generated.',
        ],

        'profile_updated_at' => [
            'label'      => 'Profile Updated',
            'definition' => 'The timestamp when the customer profile was last recalculated or updated.',
        ],

    ],

];
