INSERT IGNORE INTO currencies (code, name, symbol, symbol_position, decimal_places) VALUES
('AED','UAE Dirham','AED','before',2),
('ALL','Albanian Lek','L','before',2),
('AMD','Armenian Dram','AMD','before',2),
('AOA','Angolan Kwanza','Kz','before',2),
('ARS','Argentine Peso','ARS','before',2),
('AUD','Australian Dollar','A$','before',2),
('AZN','Azerbaijani Manat','AZN','before',2),
('BAM','Bosnia Convertible Mark','KM','before',2),
('BBD','Barbadian Dollar','Bds$','before',2),
('BDT','Bangladeshi Taka','Tk','before',2),
('BGN','Bulgarian Lev','lv','after',2),
('BHD','Bahraini Dinar','BD','before',3),
('BIF','Burundian Franc','Fr','before',0),
('BND','Brunei Dollar','B$','before',2),
('BOB','Bolivian Boliviano','Bs','before',2),
('BRL','Brazilian Real','R$','before',2),
('BWP','Botswanan Pula','P','before',2),
('BYN','Belarusian Ruble','Br','before',2),
('BZD','Belize Dollar','BZ$','before',2),
('CAD','Canadian Dollar','C$','before',2),
('CDF','Congolese Franc','Fr','before',2),
('CHF','Swiss Franc','CHF','before',2),
('CLP','Chilean Peso','CLP$','before',0),
('CNY','Chinese Yuan','CNY','before',2),
('COP','Colombian Peso','COP$','before',2),
('CRC','Costa Rican Colon','CRC','before',2),
('CUP','Cuban Peso','CUP','before',2),
('CVE','Cape Verdean Escudo','CVE','before',2),
('CZK','Czech Koruna','Kc','after',2),
('DJF','Djiboutian Franc','Fr','before',0),
('DKK','Danish Krone','kr','before',2),
('DOP','Dominican Peso','DOP$','before',2),
('DZD','Algerian Dinar','DA','before',2),
('EGP','Egyptian Pound','E.P.','before',2),
('ERN','Eritrean Nakfa','Nfk','before',2),
('ETB','Ethiopian Birr','Br','before',2),
('EUR','Euro','EUR','before',2),
('FJD','Fijian Dollar','FJ$','before',2),
('GBP','British Pound Sterling','GBP','before',2),
('GEL','Georgian Lari','GEL','before',2),
('GHS','Ghanaian Cedi','GHS','before',2),
('GMD','Gambian Dalasi','D','before',2),
('GNF','Guinean Franc','Fr','before',0),
('GTQ','Guatemalan Quetzal','Q','before',2),
('GYD','Guyanese Dollar','GY$','before',2),
('HKD','Hong Kong Dollar','HK$','before',2),
('HNL','Honduran Lempira','L','before',2),
('HTG','Haitian Gourde','G','before',2),
('HUF','Hungarian Forint','Ft','after',0),
('IDR','Indonesian Rupiah','Rp','before',0),
('ILS','Israeli New Shekel','ILS','before',2),
('INR','Indian Rupee','Rs','before',2),
('IQD','Iraqi Dinar','IQD','before',3),
('IRR','Iranian Rial','IRR','before',0),
('ISK','Icelandic Krona','kr','after',0),
('JMD','Jamaican Dollar','J$','before',2),
('JOD','Jordanian Dinar','JD','before',3),
('JPY','Japanese Yen','JPY','before',0),
('KES','Kenyan Shilling','KSh','before',2),
('KGS','Kyrgyzstani Som','KGS','before',2),
('KHR','Cambodian Riel','KHR','before',2),
('KMF','Comorian Franc','Fr','before',0),
('KRW','South Korean Won','KRW','before',0),
('KWD','Kuwaiti Dinar','KD','before',3),
('KYD','Cayman Islands Dollar','KY$','before',2),
('KZT','Kazakhstani Tenge','KZT','before',2),
('LAK','Laotian Kip','LAK','before',0),
('LBP','Lebanese Pound','LL','before',2),
('LKR','Sri Lankan Rupee','Rs','before',2),
('LRD','Liberian Dollar','L$','before',2),
('LSL','Lesotho Loti','L','before',2),
('LYD','Libyan Dinar','LD','before',3),
('MAD','Moroccan Dirham','MAD','before',2),
('MDL','Moldovan Leu','L','after',2),
('MGA','Malagasy Ariary','Ar','before',2),
('MKD','Macedonian Denar','MKD','after',2),
('MMK','Myanmar Kyat','K','before',0),
('MNT','Mongolian Togrog','MNT','before',0),
('MOP','Macanese Pataca','MOP','before',2),
('MRU','Mauritanian Ouguiya','UM','before',2),
('MUR','Mauritian Rupee','Rs','before',2),
('MVR','Maldivian Rufiyaa','Rf','before',2),
('MWK','Malawian Kwacha','MK','before',2),
('MXN','Mexican Peso','Mex$','before',2),
('MYR','Malaysian Ringgit','RM','before',2),
('MZN','Mozambican Metical','MT','before',2),
('NAD','Namibian Dollar','N$','before',2),
('NGN','Nigerian Naira','NGN','before',2),
('NIO','Nicaraguan Cordoba','C$','before',2),
('NOK','Norwegian Krone','kr','before',2),
('NPR','Nepalese Rupee','Rs','before',2),
('NZD','New Zealand Dollar','NZ$','before',2),
('OMR','Omani Rial','OMR','before',3),
('PAB','Panamanian Balboa','B/.','before',2),
('PEN','Peruvian Sol','S/','before',2),
('PGK','Papua New Guinean Kina','K','before',2),
('PHP','Philippine Peso','PHP','before',2),
('PKR','Pakistani Rupee','Rs','before',2),
('PLN','Polish Zloty','zl','after',2),
('PYG','Paraguayan Guarani','PYG','before',0),
('QAR','Qatari Riyal','QR','before',2),
('RON','Romanian Leu','lei','after',2),
('RSD','Serbian Dinar','din','after',0),
('RUB','Russian Ruble','RUB','after',2),
('RWF','Rwandan Franc','RF','before',0),
('SAR','Saudi Riyal','SR','before',2),
('SBD','Solomon Islands Dollar','SI$','before',2),
('SCR','Seychellois Rupee','Rs','before',2),
('SDG','Sudanese Pound','SDG','before',2),
('SEK','Swedish Krona','kr','before',2),
('SGD','Singapore Dollar','S$','before',2),
('SLE','Sierra Leonean Leone','Le','before',2),
('SOS','Somali Shilling','Sh','before',2),
('SRD','Surinamese Dollar','SRD','before',2),
('STN','Sao Tome Dobra','Db','before',2),
('SZL','Swazi Lilangeni','L','before',2),
('THB','Thai Baht','THB','before',2),
('TJS','Tajikistani Somoni','SM','before',2),
('TMT','Turkmenistani Manat','T','before',2),
('TND','Tunisian Dinar','DT','before',3),
('TOP','Tongan Paanga','T$','before',2),
('TRY','Turkish Lira','TRY','after',2),
('TTD','Trinidad and Tobago Dollar','TT$','before',2),
('TWD','New Taiwan Dollar','NT$','before',2),
('TZS','Tanzanian Shilling','TSh','before',0),
('UAH','Ukrainian Hryvnia','UAH','after',2),
('UGX','Ugandan Shilling','USh','before',0),
('USD','US Dollar','USD','before',2),
('UYU','Uruguayan Peso','UYU','before',0),
('UZS','Uzbekistani Som','UZS','after',0),
('VES','Venezuelan Bolivar','Bs.S','before',2),
('VND','Vietnamese Dong','VND','after',0),
('VUV','Vanuatu Vatu','Vt','before',0),
('WST','Samoan Tala','T','before',2),
('XAF','CFA Franc BEAC','Fr','before',0),
('XCD','East Caribbean Dollar','EC$','before',2),
('XOF','CFA Franc BCEAO','Fr','before',0),
('XPF','CFP Franc','Fr','before',0),
('YER','Yemeni Rial','YER','before',0),
('ZAR','South African Rand','R','before',2),
('ZMW','Zambian Kwacha','ZK','before',2),
('ZWL','Zimbabwean Dollar','Z$','before',2);
