CREATE TABLE `external_event_inbox` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `source_app` varchar(50) NOT NULL,
  `provider` varchar(50) NOT NULL,
  `event_type` varchar(100) NOT NULL,
  `event_direction` enum('inbound') NOT NULL DEFAULT 'inbound',
  `dedupe_key` varchar(191) NOT NULL,
  `company_id` bigint(20) unsigned DEFAULT NULL,
  `branch_id` bigint(20) unsigned DEFAULT NULL,
  `customer_id` bigint(20) unsigned DEFAULT NULL,
  `related_entity_type` varchar(50) DEFAULT NULL,
  `related_entity_id` bigint(20) unsigned DEFAULT NULL,
  `payload_json` longtext NOT NULL,
  `headers_json` longtext DEFAULT NULL,
  `meta_json` longtext DEFAULT NULL,
  `status` enum('pending','processing','processed','failed','dead') NOT NULL DEFAULT 'pending',
  `attempt_count` int(10) unsigned NOT NULL DEFAULT 0,
  `max_attempts` int(10) unsigned NOT NULL DEFAULT 10,
  `available_at` datetime NOT NULL DEFAULT current_timestamp(),
  `claimed_at` datetime DEFAULT NULL,
  `claimed_by` varchar(100) DEFAULT NULL,
  `processed_at` datetime DEFAULT NULL,
  `last_error` text DEFAULT NULL,
  `last_error_at` datetime DEFAULT NULL,
  `received_at` datetime NOT NULL DEFAULT current_timestamp(),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_external_event_dedupe` (`source_app`,`provider`,`event_type`,`dedupe_key`),
  KEY `idx_external_event_status_available` (`status`,`available_at`),
  KEY `idx_external_event_provider_type` (`provider`,`event_type`),
  KEY `idx_external_event_company` (`company_id`),
  KEY `idx_external_event_branch` (`branch_id`),
  KEY `idx_external_event_received` (`received_at`),
  KEY `idx_external_event_related` (`related_entity_type`,`related_entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
